FROM node:22-alpine AS builder

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/ .

RUN npm run build 



FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
